### ISSUE TITLE
Error: Execution failed.

### ISSUE THREAD

**Issue by mrigger** [kframework/c-semantics#317]
I'm using Ubuntu 17.10 and have followed the instructions for Ubuntu 16.04 in `INSTALL.md`. When using `kcc` on the `helloworld.c` test case, the following output is produced:

```
$ dist/kcc tests/unitTests/helloworld.c
Can't exec "rv-ifdefclear": No such file or directory at dist/kcc line 4488.
```
The compiled program then fails during execution:
```
$ ./a.out 
Hello world
Error: Execution failed.
```
Any ideas on how to fix this? Thanks!

**Comment by chathhorn** [comment]
I'll get this fixed asap, but in the mean time you might try the version of `kcc` downloadable here: https://runtimeverification.com/match/download/

**Comment by mrigger** [comment]
Okay, thank you!

**Comment by chathhorn** [comment]
Should be fixed now now, but reopen if not.

**Comment by mrigger** [comment]
When compiling, I no longer get the warning `Can't exec "rv-ifdefclear": No such file or directory at dist/kcc line 4488.` However, when executing the binary, there is still an error:

```c
$ ./a.out
Hello world
Error: Execution failed.
```

**Comment by h0nzZik** [comment]
Is it the `helloworld.c` file? What if you try a simpler one, or what happens if `main` just returns `0`?
```
int puts(char const *s);
int main(void)  {
        return puts("Hello world\n");
}
```

**Comment by mrigger** [comment]
The program above and this one fails (with `Error: Execution failed.`):
```c
int main(void)  {
    return 3;
}
```
This one works:
```c
int main(void)  {
    return 0;
}
```
I will try later on a different Ubuntu machine to see if that changes anything.

**Comment by h0nzZik** [comment]
And what about the following one? Maybe it just fails if the return value is nonzero.
```
int puts(char const *s);
int main(void)  {
        puts("Hello world\n");
        return 0;
}
```

**Comment by mrigger** [comment]
You are right, if the return value is zero then this and more complex programs execute as expected. Thank you!
